### PR TITLE
Webhook Handlers

### PR DESCRIPTION
**Pull request by keysolutions**
Adds an API to simplify the handling of webhook requests.

Example usage:

```ruby
notification = Recurly::Webhook.parse(xml_body)

case notification
when Recurly::Webhook::NewAccountNoficiation

  # A new account was created
  puts "New account #{notification.account.account_code}"

when Recurly::Webhook::NewSubscriptionNotification

  # A new subscription was added
  puts "New subscription from #{notification.account.account_code}"
  
  # Notifications are not necessarily current. ! relation methods will
  # fetch the latest data
  puts "Current state #{notification.subscription!.state}"

when Recurly::Webhook::SubscriptionNotification

  # A subscription-related notification was sent
  puts "Generic subscription notification by #{notification.account!.account_code}"

end
```

### CODE REVIEW

**Comment by bhelx** [comment]
@keysolutions This is kind of big but I still want to merge this. Are you still interested in having it merged?

**Comment by bhelx** [comment]
@keysolutions This is great work BTW

**Comment by dsshap** [comment]
Any plans to merge this in and release?

**Comment by bhelx** [comment]
@dsshap i'd need to review each field as it was written about a year ago. @keysolutions appears to have abandoned it. If you want to pick up the torch I would be happy to get it merged. All that's needed it to go through and update all the specs and fields to make sure they are current.

**Comment by dsshap** [comment]
@bhelx what do you mean review each field?

I forked the recurly repo and cherry picked the relevant commits and only one test failed, but looks like its not related to this pull request.

```
Finished tests in 0.932608s, 264.8487 tests/s, 464.2894 assertions/s.

  1) Failure:
test_0001_must_filter_sensitive_data_only_on_number_and_verification_value(Recurly::XML::.filter) [/Users/dave/Documents/scout/workspace/recurly-client-ruby/spec/recurly/xml_spec.rb:28]:
--- expected
+++ actual
@@ -1 +1 @@
-"<account><billing_info><number></number></billing_info></account>"
+"<account><billing_info><number/></billing_info></account>"


247 tests, 433 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by bhelx** [comment]
I'm unsure if any fields have changed or been added on our end since the time it was written.

**Comment by bhelx** [comment]
Would have to be checked here: https://recurly.readme.io/v2.0/page/webhooks

**Comment by dsshap** [comment]
@bhelx I don't have the bandwidth right now to check for you, but speaking from a soon to be paying customer, it would be helpful is this was merged in.

**Comment by bhelx** [comment]
@dsshap I'll see if I can prioritize it

**Comment by bhelx** [comment]
@dsshap Had some time this morning. Let's finish the conversation here: https://github.com/recurly/recurly-client-ruby/pull/217

**Pull request closed without merging**
