### PR TITLE
Threadsafe Recurly.api_key

### PR DESCRIPTION
**Pull request by ivanovv**
Very straightforward solution, which brings a undesired behaviour - code, that relies on Recurly.api_key being set by some other thread,  will fail.
So, second commit to fix this issue, but for a main thread only - if you set Recurly.api_key in the main thread, it will be avail to all threads run afterwards. 
But if any of these threads sets its own key - it will use its own key.

### CODE REVIEW

**Comment by chrissrogers** [comment]
Related to issue recurly/recurly-client-ruby#159

**Comment by chrissrogers** [comment]
I don't want to close this as it is an important feature for some. However, I am still hesitant to introduce `Thread.current` references to all users.

**Comment by bhelx** [comment]
I agree. I think it's a design flaw. You should have to instantiate the api client given some credentials/subdomain as @chrissrogers mentioned. I'm also hesitant to solve it like this because we can't say for sure how it's going to work in everyone's environments and it would be a really difficult thing to debug.

Perhaps we can think of a way to support both using this current singleton API technique and also the instantiable way, then we can later deprecate the singleton way. I think I have a few ideas to do it. What do you think @chrissrogers ?

**Comment by chrissrogers** [comment]
I support that path. It will take modifying all of the singleton calling patterns to on-instance calls. Basically every module will need to be instantiable and live on an instantiable Recurly. A singleton for backward compatibility will be easy to wrap around that.

**Comment by ciddennis** [comment]
I created another pull request with my solution to this issue.  https://github.com/recurly/recurly-client-ruby/pull/190.

**Comment by bhelx** [comment]
Well, after looking at doing an instantiable API object, it does seem like too big of a pattern change. I still want to get something in for these people.

I'm open to this solution as long as it doesn't affect people who are currently using accessing single accounts in a multithreaded environment. @ivanovv could you maybe add a test that proves this? Maybe something like this:

```ruby
    it "has the same config values unless a new one is set in the new thread" do
      Recurly.api_key = "123"
      Recurly.subdomain = "test"
      Recurly.default_currency = "USD"
      Thread.new do
        Recurly.api_key.must_equal "123"
        Recurly.subdomain.must_equal "test"
        Recurly.default_currency.must_equal "USD"
        Recurly.api_key = "456"
        Recurly.subdomain = "thread_test"
        Recurly.default_currency = "HKD"
        Recurly.api_key.must_equal "456"
        Recurly.subdomain.must_equal "thread_test"
        Recurly.default_currency.must_equal "HKD"
      end.join
      Recurly.api_key.must_equal "123"
      Recurly.subdomain.must_equal "thread_test"
      Recurly.default_currency.must_equal "USD"
    end
```

I don't think you are properly handling subdomains, default_currency, and the js config.

**Comment by bhelx** [comment]
Fixed with https://github.com/recurly/recurly-client-ruby/pull/190

**Pull request closed without merging**
